config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  get "/users", to: "users#index", as:"users"
  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"
  get "/members", to: "users#show_all", as: "show_users"

  get "/login", to: "sessions#new", as: "login"
  post "/sessions", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: "logout"

  get "/libraries", to: "libraries#index", as: "libraries"
  get "/libraries/new", to: "libraries#new", as: "new_library"
  post "/libraries", to: "libraries#create"
  get "/libraries/:id", to: "libraries#show", as: "library"
  delete "/libraries/:id", to: "libraries#destroy", as: "delete_library"
  get "/libraries/:id/edit", to: "libraries#edit", as: "edit_library"
  patch "/libraries/:id", to: "libraries#update"

  get "/users/:user_id/libraries", to: "library_users#index", as: "user_libraries"
  post "/libraries/:library_id/users", to: "library_users#create", as: "library_users"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :library_users, dependent: :destroy
  has_many :users, through: :library_users
end

app/models/library_user.rb
class LibraryUser < ApplicationRecord
  belongs_to :user
  belongs_to :library
end

app/models/user.rb
class User < ApplicationRecord
  has_many :library_users, dependent: :destroy
  has_many :libraries, through: :library_users

  has_secure_password
  validates :first_name, :last_name, presence: true, length: {minimum: 2}
  validates :email, format: {with: /.@./}, presence: true, uniqueness: true
  validates :password, presence: true, length: {minimum: 8, maximum: 20}, on: :create

  def self.confirm(params)
    user = User.find_by_email(params[:email])
    user ? user.authenticate(params[:password]) : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
    @libraries = Library.all
  end

  def new
    @library = Library.new
  end

  def create
    @library = Library.create(library_params)
    redirect_to libraries_path
  end

  def show
    @library = Library.find_by_id(params[:id])
  end

  def destroy
    @library = Library.find_by_id(params[:id])
    @library.delete
    redirect_to libraries_path
  end

  def edit
    @library = Library.find_by_id(params[:id])
  end

  def update
    @library = Library.find_by_id(params[:id])
    @library.update_attributes(library_params)
    redirect_to libraries_path
  end

  private
  def library_params
    params.require(:library).permit(:name, :floor_count, :floor_area)
  end
end

app/controllers/library_users_controller.rb
class LibraryUsersController < ApplicationController
  include SessionsHelper
  def index
    @user = User.find_by_id(params[:user_id])
    @libraries = @user.libraries
  end

  def create
    @library = Library.find(params[:library_id])
    @library.users.push(current_user)  # no error handling currently

    redirect_to current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    user = User.confirm(user_params)
    if user
      login(user)
      redirect_to user_path(user)
    else
      redirect_to login_path(user)
    end
  end

  def destroy
    logout
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorization, except: [:index, :new, :create]
  include SessionsHelper

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to user_path(user)
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def authorization
    user = User.find_by_id(params[:id])
    if !current_user
      flash[:notice] = "You have to log in first!"
      redirect_to login_path
    elsif params[:id] && current_user!=user
      flash[:notice] = "You're not allowed to see other users personal pages!"
      redirect_to user_path(current_user)
    end
  end

  def show_all
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/library_users_helper.rb
module LibraryUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PublicLibraryApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <h3>
    <ul>
      <li><%=link_to "Libraries", libraries_path%></li>
      <% if current_user %>
        <li><%=link_to "See your profile", user_path(current_user)%></li>
        <li><%=link_to "Log Out", logout_path%></li>
        <li><%=link_to "All library members", show_users_path%></li>
      <%else%>
        <li><%=link_to "Create account", new_user_path(current_user)%></li>
        <li><%=link_to "Log In", login_path(current_user)%></li>
      <%end%>
    </ul>
    </h3>
  </header>
    <%flash.each do |name, msg|%>
    <span style="color: red"><%=msg%></span>
      <%end%>
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= yield %>
          </div>
        </div>
      </div>
  </body>
</html>

app/views/libraries/edit.html.erb
<%=form_for @library do |f|%>
  <div>
    <%=f.text_field :name, placeholder: "name", class: "form-control"%>
  </div>
  <div>
    <%=f.number_field :floor_count, placeholder: "floor count", class: "form-control"%>
  </div>
  <div>
    <%=f.number_field :floor_area, placeholder: "name", class: "form-control"%>
  </div>
  <%=f.submit "Save changes"%>
<%end%>

app/views/libraries/index.html.erb
<% @libraries.each do |library| %>
  <div>
    <h3><%= library.name %></h3>
    <%=link_to "Show", library_path(library)%>
    <%=link_to "Edit", edit_library_path(library)%>
    <% if current_user %>
      <%= button_to "Join", library_users_path(library) %>
    <% end %>
    <%=link_to "Delete", delete_library_path(library), method: :delete%>
  </div>
  <br>
<% end %>
<%=link_to "Add new", new_library_path%>

app/views/libraries/new.html.erb
<%=form_for @library do |f|%>
  <div>
    <%=f.text_field :name, placeholder: "name", class: "form-control"%>
  </div>
  <div>
    <%=f.number_field :floor_count, placeholder: "floor count", class: "form-control"%>
  </div>
  <div>
    <%=f.number_field :floor_area, placeholder: "name", class: "form-control"%>
  </div>
  <%=f.submit "Add library"%>
<%end%>

app/views/libraries/show.html.erb
<h3><%= @library.name %></h3>
<h4>Floor: <%= @library.floor_count %></h4>
<h4>Floor area: <%= @library.floor_area %></h4>
<%=link_to "Back", libraries_path%>

app/views/library_users/index.html.erb
<div><%= @user.first_name %> is a member of the following libraries</div>

<ul>
  <% @libraries.each do |lib| %>
    <li><%= lib.name %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1><%=@users.size%> users signed up!</h1>

app/views/users/new.html.erb
<h1>Creating new account</h1>
<hr>
<%=form_for @user do |f|%>
  <%=f.text_field :first_name, placeholder: "first name", class: "form-control"%>
  <%=f.text_field :last_name, placeholder: "last name", class: "form-control"%>
  <%=f.email_field :email, placeholder: "email", class: "form-control"%>
  <%=f.password_field :password, placeholder: "password", class: "form-control"%>
  <%=f.password_field :password_confirmation, placeholder: "password confirmation", class: "form-control"%>
  <%=f.submit "Create account", class: "btn btn-success"%>
<%end%>

app/views/users/show.html.erb
<h1><%=@user.first_name%> <%=@user.last_name%></h1>
<h3>Created at: <%=@user.created_at.strftime("%m/%d/%Y %I:%M%p")%></h3>

app/views/users/show_all.html.erb
<%@users.each do |user|%>
  <h3><%=user.first_name%> <%=user.last_name%></h3>
<%end%>